version: '2.1'

services:
  ekklesia-oradea:
    image: ekklesia-oradea
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9229:9229
    ## set your startup file here
    command: node --inspect main.js
